Repository wavvapp/sac-frontend, pull requests merged in 2024-11, with the labels that each got.

#97 refactor: implement search screen on the frontend
  .gitignore
  components/ui/UserAvatar.tsx
  contexts/AuthContext.tsx
  screens/Search/index.tsx
  service/index.ts
Labels: ready for senior review

#106 feat: remove login screen
  navigation/index.tsx
  screens/Authentication/Login/index.tsx
  screens/Authentication/SignUp/index.tsx
  screens/Authentication/index.tsx
Labels: ready for senior review

#96 Feat: fetch and display user from the backend
  .gitignore
  components/cards/UserStatus.tsx
  contexts/AuthContext.tsx
  hooks/useSignal.ts
  screens/EditSignal/index.tsx
  screens/Home/index.tsx
  screens/Search/index.tsx
  service/index.ts
Labels: ready for senior review

#110 feat: create friendship
  screens/Search/index.tsx
  types/index.ts
Labels: ready for peer review, ready for senior review

#102 Feat: update account with username
  components/cards/NoFriends.tsx
  contexts/AuthContext.tsx
  navigation/index.tsx
  screens/Authentication/SignUp/CreateCredentials.tsx
  types/index.ts
Labels: ready for peer review, ready for senior review

#109 ft/update user activity status
  App.tsx
  components/Activity.tsx
  components/Friend.tsx
  components/cards/Status.tsx
  components/cards/UserStatus.tsx
  components/lists/Friends.tsx
  components/lists/Signaling.tsx
  components/ui/UserAvatar.tsx
  contexts/AuthContext.tsx
  contexts/StatusContext.tsx
  navigation/index.tsx
  screens/EditActivity/index.tsx
  screens/EditSignal/index.tsx
  service/index.ts
  types/index.ts
Labels: ready for senior review

#100 feat: Fetch signaling from the backend
  components/cards/NoFriends.tsx
  components/cards/UserStatus.tsx
  components/lists/Signaling.tsx
  hooks/useFriends.ts
  screens/CustomSplashScreen/index.tsx
  screens/Home/index.tsx
  types/index.ts
Labels: ready for peer review, ready for senior review

#123 Style: reduce the icon-header padding top
  screens/Authentication/SignUp/CreateCredentials.tsx
  screens/Home/index.tsx
Labels: ready for peer review

#121 Feat:add done btn to the edit activity form
  components/ui/Input.tsx
  components/vectors/CheckIcon.tsx
  screens/EditActivity/index.tsx
Labels: ready for peer review

#119 refactor: add loader state while saving activity status
  components/ui/Button.tsx
  screens/EditSignal/index.tsx
Labels: ready for peer review

#126 feat: add loader when users and friends request are pending
  components/cards/FriendsSkeleton.tsx
  data/users.ts
  hooks/.useFriends.ts.swp
  screens/Authentication/index.tsx
  screens/CustomSplashScreen/index.tsx
  screens/Search/index.tsx
Labels: ready for peer review

#125 fix: remove showing that user has no friends when they do
  hooks/useFriends.ts
  navigation/index.tsx
  types/index.ts
Labels: ready for peer review

#132 Feat: add safeAreaView
  App.tsx
  screens/Authentication/SignUp/CreateCredentials.tsx
  screens/Home/index.tsx
Labels: ready for peer review

#122 refactor: set signal activity status to initials status from the backend
  components/Activity.tsx
  components/lists/Friends.tsx
  contexts/StatusContext.tsx
  hooks/useSignal.ts
Labels: ready for peer review

#135 feat: provide instant feedbacks to the user before the backend responds
  components/lists/Friends.tsx
  components/lists/Signaling.tsx
  contexts/StatusContext.tsx
  hooks/.useFriends.ts.swp
  hooks/useFriends.ts
  hooks/useSignal.ts
  navigation/index.tsx
  screens/EditSignal/index.tsx
  screens/Home/index.tsx
Labels: ready for peer review

#143 fix: design when no friends available
  components/lists/Signaling.tsx
Labels: ready for senior review

#142 fix: go back to home screen when crossmark is checked
  screens/EditSignal/index.tsx
Labels: ready for peer review

#130 refactor: add loader while fetching friends inside edit activity screen
  components/Friend.tsx
  components/lists/Friends.tsx
  components/lists/Signaling.tsx
  hooks/useFriends.ts
  hooks/useSignal.ts
  screens/Authentication/SignUp/index.tsx
  screens/Home/index.tsx
Labels: ready for peer review

#138 Fix: signaling list scroll
  components/Activity.tsx
  components/SignalingUser.tsx
  components/cards/Status.tsx
  components/lists/Signaling.tsx
  screens/Home/index.tsx
Labels: ready for peer review

#153 fix: open the edit screen when the button is clicked instantly
  components/cards/UserStatus.tsx
  screens/EditSignal/index.tsx
Labels: ready for peer review

#165 fix: remvoe points loader
  components/cards/BadgeSkeleton.tsx
  screens/Home/index.tsx
Labels: ready for peer review

#147 refactor: adding spinning icon while adding friends
  screens/Search/index.tsx
Labels: ready for peer review

#152 fix: signal friends when click on the plus icon
  components/Friend.tsx
  components/ui/CheckBox.tsx
Labels: ready for peer review
