Repository wavvapp/sac-frontend, pull requests merged in 2025-01, with the labels that each got.

#247 Fix : Remove unnecessary space on names with first names only in userStatus card
  components/cards/UserStatus.tsx
Labels: ready for peer review

#248 create an offline-popup when there is no internet connection
  components/AlertDialog.tsx
  theme.ts
Labels: ready for peer review

#257 feat/sort friends alphabetically and show selected friends first
  components/cards/UserStatus.tsx
  components/lists/Friends.tsx
Labels: ready for peer review

#250 feat: check the network connectivity
  components/AlertDialog.tsx
  components/lists/Signaling.tsx
  contexts/AuthContext.tsx
  hooks/useOfflineHandler.ts
  navigation/index.tsx
  package-lock.json
  package.json
  screens/EditSignal/index.tsx
  screens/Home/index.tsx
  screens/Search/index.tsx
  service/index.ts
  types/index.ts
Labels: ready for peer review

#270 send user's current timezone in headers to the backend
  service/index.ts
Labels: ready for peer review

#268 refactor: remove hardcoded variables
  .env.example
  components/cards/Action.tsx
  components/cards/Header.tsx
  screens/Authentication/SignUp/index.tsx
  screens/Authentication/index.tsx
  screens/Home/index.tsx
  screens/StaticContentScreen/index.tsx
  theme.ts
Labels: ready for peer review

#274 Fix: Show the keyboard by default when user is editing the status
  components/Activity.tsx
  components/ui/Input.tsx
  screens/EditActivity/index.tsx
Labels: ready for senior review

#269 Feat: Create dimensions file
  components/PerlinNoise/index.tsx
  components/lists/Signaling.tsx
  screens/Authentication/index.tsx
  screens/Home/index.tsx
  utils/dimensions.ts
Labels: ready for senior review

#271 refactor: change parameter name from page to pageSlug
  navigation/index.tsx
  screens/Authentication/index.tsx
  screens/StaticContentScreen/index.tsx
Labels: ready for peer review

#281 feat: create user profile component
  components/UserInfo.tsx
  components/cards/UserProfile.tsx
  components/ui/UserAvatar.tsx
  screens/Settings/index.tsx
Labels: ready for peer review, ready for senior review

#280 Feat: Modify EditActivity to be re-usable
  components/Activity.tsx
  components/BottomModal.tsx
  screens/EditActivity/index.tsx
Labels: ready for peer review

#282 refactor/update alert dialog component
  components/AlertDialog.tsx
  components/ui/Button.tsx
  types/index.ts
Labels: ready for senior review

#293 refactor: update logout button text
  screens/Settings/index.tsx
Labels: ready for peer review

#286 Feat/change flow of share flow
  components/AlertDialog.tsx
  components/Share.tsx
  components/cards/CopiableText.tsx
  constants/links.ts
  contexts/AuthContext.tsx
  navigation/index.tsx
  package-lock.json
  package.json
  screens/Home/index.tsx
  screens/Search/index.tsx
  screens/Settings/index.tsx
  tsconfig.json
  types/index.ts
  utils/share.ts
Labels: ready for peer review

#294 feat: unfriend a user
  queries/friends.ts
  screens/Search/index.tsx
Labels: ready for peer review

#296 ft/delete account
  queries/user.ts
  screens/Settings/index.tsx
Labels: ready for peer review

#295 Feat: edit user info
  contexts/AuthContext.tsx
  hooks/useUpdateUser.ts
  queries/user.ts
  screens/EditActivity/index.tsx
  screens/Settings/index.tsx
Labels: ready for peer review

#298 Fix: add max-width for the dialog
  components/AlertDialog.tsx
Labels: ready for peer review

#284 feat: add code verification step in account setup
  components/CredentialsButton.tsx
  constants/account-setup-steps.ts
  constants/patterns.ts
  contexts/AuthContext.tsx
  screens/Authentication/SignUp/CreateCredentials.tsx
  screens/EditSignal/index.tsx
  screens/Home/index.tsx
  screens/Search/index.tsx
  screens/Settings/index.tsx
  types/index.ts
  utils/share.ts
Labels: ready for peer review

#302 feat: add verification fields and update app version
  app.json
  components/cards/ConfirmationCode.tsx
  constants/patterns.ts
  package-lock.json
  package.json
  screens/Authentication/SignUp/CreateCredentials.tsx
Labels: ready for peer review
