Repository wavvapp/sac-frontend, pull requests merged in 2025-02, with the labels that each got.

#288 Style: add bellicon to the signaling user component
  components/SignalingUser.tsx
  components/lists/Signaling.tsx
Labels: ready for peer review, ready for senior review

#309 feat: add NotificationPreferences screen
  components/BottomDrawer.tsx
  components/ui/CustomSwitch.tsx
  navigation/index.tsx
  screens/NotificationPreferences/index.tsx
  screens/Settings/index.tsx
Labels: ready for peer review

#307 Fix: Tap to edit functionality
  contexts/AuthContext.tsx
Labels: ready for peer review

#320 refactor: update none of your friends online text
  components/lists/Signaling.tsx
Labels: ready for peer review

#328 refactor: update the auto-invite message on Share
  utils/share.ts
Labels: ready for peer review

#321 feat: swap user full names
  components/CredentialsButton.tsx
  constants/account-setup-steps.ts
  contexts/AuthContext.tsx
  libs/handleApiSignIn.ts
  screens/Authentication/SignUp/CreateCredentials.tsx
  types/index.ts
  utils/index.ts
Labels: ready for peer review

#329 feat/receive notifications from firebase in the app
  components/SignalingUser.tsx
  components/lists/Friends.tsx
  components/lists/Signaling.tsx
  queries/friends.ts
  types/index.ts
Labels: ready for peer review

#326 feat: add noise Video
  assets/videos/signal_background.mp4
  components/NoiseVideo.tsx
  package-lock.json
  package.json
  screens/Authentication/index.tsx
  screens/CustomSplashScreen/index.tsx
  screens/Home/index.tsx
Labels: ready for peer review

#330 feat: integrate notification preferences with the backend
  components/AlertDialog.tsx
  components/SignalingUser.tsx
  components/ui/CustomSwitch.tsx
  hooks/useEnableFriendNotification.ts
  queries/friends.ts
  screens/NotificationPreferences/index.tsx
  screens/Search/index.tsx
Labels: ready for peer review

#332 feat: update version and disable tablet
  app.json
  package.json
Labels: ready for peer review

#350 fix: change the full name placeholder
  constants/account-setup-steps.ts
Labels: ready for peer review

#354 fix: change the body text font
  components/AlertDialog.tsx
Labels: ready for peer review

#355 feat: change android notification icon
  assets/images/favicon.png
Labels: ready for peer review

#353 Fix: fonts and size in the edit status screen
  components/Activity.tsx
  components/cards/Status.tsx
  components/lists/Friends.tsx
Labels: ready for peer review

#351 fix: center NoFriends card
  screens/Home/index.tsx
Labels: ready for peer review

#356 fix Status line spacing
  components/cards/UserStatus.tsx
  package-lock.json
Labels: ready for peer review

#357 Fix: semibold font weight on android
  components/AlertDialog.tsx
  components/AnimatedSwitch/index.tsx
  components/cards/Action.tsx
  components/cards/Header.tsx
  components/lists/Signaling.tsx
  theme.ts
Labels: ready for peer review

#359 Feat: update alert dialog spacings
  components/AlertDialog.tsx
Labels: ready for peer review

#363 Fix: semibold on ios
  theme.ts
Labels: ready for peer review

#389 Feat: update notification action card
  components/cards/Action.tsx
  components/cards/FriendsSkeleton.tsx
  screens/EditSignal/index.tsx
  screens/Search/index.tsx
  screens/Settings/index.tsx
Labels: ready for peer review

#379 Fix/scrollable settings screen
  screens/Settings/index.tsx
Labels: ready for senior review

#394 feat/update the find button
  components/SignalingUser.tsx
  components/lists/Signaling.tsx
  components/vectors/SearchIcon.tsx
Labels: ready for peer review

#393 fix Bug/the icon buttons spacing
  components/Activity.tsx
  components/cards/Header.tsx
  screens/Home/index.tsx
  screens/Settings/index.tsx
Labels: ready for peer review

#391 feat: update user status card
  components/cards/UserAvailability.tsx
  components/cards/UserStatus.tsx
Labels: ready for peer review

#396 feat: implement the new homescreen tap design
  components/AnimatedSwitch/index.tsx
  components/cards/TapWavv.tsx
  components/cards/UserStatus.tsx
  screens/Home/index.tsx
Labels: ready for peer review

#390 fix: all buttons's styles and add a 'turn off your wavv' button
  components/cards/NoFriends.tsx
  components/ui/Button.tsx
  screens/EditSignal/index.tsx
  screens/Search/index.tsx
Labels: ready for peer review
