Repository wavvapp/sac-frontend, pull requests merged in 2025-03, with the labels that each got.

#395 feat: update edit signal screen
  components/Activity.tsx
  components/cards/Status.tsx
  components/cards/TapWavv.tsx
  components/cards/UserStatus.tsx
  components/lists/Friends.tsx
  components/ui/Badge.tsx
  components/ui/CustomTitle.tsx
  navigation/index.tsx
  screens/EditActivity/index.tsx
  screens/EditSignal/index.tsx
Labels: ready for peer review

#402 Style: Change spacings in the "editSignal" screen
  components/Activity.tsx
  components/cards/Status.tsx
  components/lists/Friends.tsx
  components/ui/CheckBox.tsx
  screens/EditActivity/index.tsx
  screens/EditSignal/index.tsx
Labels: ready for senior review

#404 refactor: move the queries and mutiations to separate files
  contexts/AuthContext.tsx
  queries/friends.ts
  queries/points.ts
  queries/signal.ts
  queries/user.ts
  screens/EditSignal/index.tsx
  screens/Home/index.tsx
  screens/Search/index.tsx
Labels: ready for peer review

#403 Feat: select all friends feature
  components/lists/Friends.tsx
  components/ui/CustomTitle.tsx
Labels: ready for peer review

#411 feat: update select all design
  components/lists/Friends.tsx
Labels: ready for peer review

#416 feat: add signal default options when setting signal for the first time
  components/Activity.tsx
  components/BottomDrawer.tsx
  components/SetActivity.tsx
  data/default-wavv-options.ts
  screens/EditSignal/index.tsx
Labels: ready for peer review

#420 Refactor: Signal editing optimistic update
  screens/EditSignal/index.tsx
Labels: ready for peer review

#422 fix: update spacing of the notification preferences list
  screens/NotificationPreferences/index.tsx
Labels: ready for peer review

#426 fix: improve friends notification enabling instant
  components/lists/Signaling.tsx
  hooks/useEnableFriendNotification.ts
  queries/friends.ts
  types/index.ts
Labels: ready for peer review

#432 refactor: update styles
  components/SetActivity.tsx
  components/cards/Header.tsx
  components/lists/Friends.tsx
  components/ui/Badge.tsx
  screens/EditSignal/index.tsx
Labels: ready for peer review

#431 feat: Add notification badges
  App.tsx
Labels: ready for peer review, ready for senior review

#441 refactor: remove turnSignal request
  queries/signal.ts
  screens/EditSignal/index.tsx
Labels: ready for peer review

#447 feat: Manage groups screen
  components/cards/Action.tsx
  components/cards/ActionHeader.tsx
  components/ui/HeaderWrapper.tsx
  components/vectors/LeftArrow.tsx
  components/vectors/UsersIcon.tsx
  navigation/index.tsx
  queries/groups.ts
  screens/Groups/CreateGroup.tsx
  screens/Groups/index.tsx
  screens/Settings/index.tsx
  theme.ts
  types/index.ts
Labels: ready for peer review

#455 Fix: show non of your fiends wavved when onlineFriends is empty
  components/lists/Signaling.tsx
Labels: ready for peer review

#453 feat: set status text to empty when its one of the options
  components/SetActivity.tsx
Labels: ready for peer review

#463 feat: display group info in the bottom sheet
  screens/Groups/index.tsx
  types/index.ts
Labels: ready for peer review

#421 feat: add proper date picker
  components/DatePicker.tsx
  components/DatePickerModal.tsx
  components/cards/Status.tsx
  constants/DateFormatter.ts
  contexts/StatusContext.tsx
  package-lock.json
  package.json
  screens/EditSignal/index.tsx
  types/index.ts
Labels: ready for peer review

#465 fix: fetch signal friends list on focus and on notification
  components/lists/Signaling.tsx
  queries/friends.ts
  screens/NotificationPreferences/index.tsx
Labels: ready for peer review

#467 fix: points badge showing on top of bottom drawer
  components/BottomDrawer.tsx
Labels: ready for peer review

#446 fix: remove the lines limit on the signal activity
  components/SetActivity.tsx
  components/cards/UserAvailability.tsx
  components/cards/UserStatus.tsx
  package-lock.json
Labels: ready for peer review

#466 Ft/delete group and optimise
  queries/groups.ts
  screens/Groups/index.tsx
Labels: ready for peer review

#472 H-fix: status options should not not open automatically
  screens/EditSignal/index.tsx
Labels: ready for peer review

#475 fix: prefetch friends signal
  contexts/AuthContext.tsx
  queries/friends.ts
Labels: ready for peer review

#491 feat: add download link side the shared link
  utils/share.ts
Labels: ready for peer review

#481 fix: signal client evaluation
  contexts/StatusContext.tsx
  queries/signal.ts
  screens/EditSignal/index.tsx
  types/index.ts
Labels: ready for peer review

#492 feat: highlight timeslot at all times
  components/DatePicker.tsx
  components/cards/Status.tsx
  contexts/StatusContext.tsx
  queries/signal.ts
  screens/EditSignal/index.tsx
Labels: ready for peer review

#462 Feat/edit groups details
  components/GroupForm.tsx
  navigation/index.tsx
  queries/groups.ts
  screens/Groups/CreateGroup.tsx
  screens/Groups/EditGroups.tsx
  screens/Groups/index.tsx
  service/index.ts
  utils/registerForNotifications.ts
Labels: ready for peer review

#499 fix: add appstate listener to watch if date has ended
  contexts/StatusContext.tsx
Labels: ready for peer review

#501 fix: open date picker if the signal has a custom timeslot
  components/DatePicker.tsx
  components/cards/Status.tsx
Labels: ready for peer review
